title: "BC-TECH"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md

markdown: kramdown

repository: "JyouJyou/bc-tech-documentation"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
